conf/urls.py
from __future__ import (
    absolute_import,
)

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from django.views.generic import TemplateView

from users import urls as users_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(users_urls, namespace='users')),
	url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^profile/', TemplateView.as_view(template_name='user/profile.html')),
    url(r'^purchase/', TemplateView.as_view(template_name='user/purchase.html')),
    url(r'^achievements/', TemplateView.as_view(template_name='user/achievements.html')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unlockpaidfeatures/urls.py
from django.conf.urls import patterns, include, url

from unlockpaidfeatures.views import SettingsView

urlpatterns = patterns('',
    url(r'^$', SettingsView.as_view(), name='change'),
    url(r'^settings/', SettingsView.as_view(), name='change'),
)

users/urls.py
from django.conf.urls import url, include

from users.views import (
	DashboardView,
    LoginView,
    LogoutView,
)
from django.views.generic import TemplateView

from users import views


urlpatterns = [
    url(r'^dashboard/$',DashboardView.as_view(template_name='user/profile.html'), name="dashboard"),
    url(r'^logout$', LogoutView.as_view(), name="logout"),
    url(r'^payment-url/$', views.buy_my_item, name='pay'),
    url(r'^some/obscure/name/', include('paypal.standard.ipn.urls')),
    url(r'^$', LoginView.as_view(template_name='user/index.html'), name='login'),

]

queue/models.py
from django.contrib.auth.models import User
from django.db import models

from adminsortable.models import Sortable
from djcelery.models import PeriodicTask

optional = {
    'blank': True,
    'null': True,
}


class Posts(models.Model):

    user = models.ForeignKey(User, related_name='posts')
    content = models.TextField()
    task = models.ForeignKey(PeriodicTask, **optional)
    bot = models.ForeignKey('Bots')
    status = models.BooleanField(default=False)

    def __unicode__(self):
        return "{}".format(self.user.get_full_name())

    class Meta:
        verbose_name_plural = 'Posts'


class Bots(Sortable):

    SMTP = 'smtp'
    PLURK = 'plurk'
    TWITTER = 'twitter'
    FACEBOOK = 'facebook'

    social_media_choices = (
        (SMTP, 'Email'),
        (PLURK, 'Plurk'),
        (TWITTER, 'Twitter'),
        (FACEBOOK, 'Facebook'),
    )

    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='bots')
    price = models.IntegerField()
    description = models.TextField()
    social_media = models.CharField(max_length=255, choices=social_media_choices)
    is_active = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    class Meta(Sortable.Meta):
        verbose_name_plural = "Bots"

unlockpaidfeatures/models.py
from django.db import models

users/models.py
from django.contrib.auth.models import User
from django.db import models

from queue.models import Bots

optional = {
    'blank': True,
    'null': True
}


class UserProfile(models.Model):

    user = models.ForeignKey(User, related_name='profile')
    coins = models.IntegerField(default=0)
    bots = models.ManyToManyField(Bots)

    def __unicode__(self):
        return "{}".format(self.user.get_full_name())

    @property
    def available_choices(self):
        choices = list(Bots.social_media_choices)
        unlocked_bots = [bot.social_media for bot in self.bots.all()]

        for choice in list(Bots.social_media_choices):
            if choice[0] not in unlocked_bots:
                choices.remove(choice)
        return tuple(choices)


class Achievement(models.Model):

    name = models.CharField(max_length=255)
    minimum_posts = models.IntegerField()
    reward = models.IntegerField()

    def __unicode__(self):
        return self.name


class Redeem(models.Model):

    achievement = models.ForeignKey(Achievement)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return "{}".format(self.user.get_full_name())

unlockpaidfeatures/forms.py
from django import forms

from queue.models import Bots

my_choices = Bots.social_media_choices

class BotsForms(forms.Form):
	choice = forms.ChoiceField(choices=my_choices)

queue/views.py
from django.shortcuts import render

# Create your views here.

unlockpaidfeatures/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.core import urlresolvers
from django.contrib import messages

<<<<<<< HEAD
from users.models import Achievement, UserProfile
=======
from users.models import Achievement, Redeem, UserProfile
>>>>>>> feff904eaad24188a6f39bef6a41b0dfa75cc846
from queue.models import Bots
from unlockpaidfeatures.forms import BotsForms

class SettingsView(View):

    def get(self, request, *args, **kwargs):
<<<<<<< HEAD
        user = request.user
        profile = user.profile.first()
        bots = profile.bots.all()
        coins = profile.coins

        botsmeta = []

        for bot, imgpair in zip(bots, (
            ('/static/img/R10.png', '/static/img/R11.png'),
            ('/static/img/R20.png', '/static/img/R21.png'),
            ('/static/img/R30.png', '/static/img/R31.png'),
            ('/static/img/R40.png', '/static/img/R41.png'),
        )):
            openimg, lockimg = imgpair
            botsmeta.append({
                'image': openimg if coins >= bot.price else lockimg,
                'bot': bot,
            })
        
        return render(request, 'user/achievements.html', {
            'botsmeta': botsmeta,
        })
=======
        context = {}
        context['bots'] = UserProfile.object.get('bots')
        coins = UserProfile.object.get('coins')
        price = Bots.object.get('price')
        image = Bots.object.get('image')
        for bot in bots
            if coins >= price
                image = 
            return render(request, 'user/test.html', context)
>>>>>>> feff904eaad24188a6f39bef6a41b0dfa75cc846

users/views.py
from django.contrib import auth
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core import urlresolvers
from django.views.generic import View

from braces.views import LoginRequiredMixin

	#paypal
from paypal.pro.views import PayPalPro

class DashboardView(LoginRequiredMixin, View):
				
	template_name = 'user/profile.html'

	def get(self, request, *args, **kwargs):
		context = {}
		if request.user.is_authenticated():
			return render(request, self.template_name, context)


class LoginView(View):

	template_name = 'user/index.html'

	def get(self, request, *args, **kwargs):
		context = {}
		if request.user.is_authenticated():
			return HttpResponseRedirect(urlresolvers.reverse('users:dashboard'))
		else: 
			return render(request, self.template_name, context)


class LogoutView(LoginRequiredMixin, View):

	template_name = 'user/index.html'
	context = {}

	def get(self, request, *args, **kwargs):
		auth.logout(request)
		return HttpResponseRedirect(urlresolvers.reverse('users:login'))



#paypal


def nvp_handler(nvp):
# This is passed a PayPalNVP object when payment succeeds.
# This should do something useful!
	pass

def buy_my_item(request):
    	item = {"paymentrequest_0_amt": "10.00",  # amount to charge for item
            "inv": "inventory",         # unique tracking variable paypal
            "custom": "tracking",       # custom tracking variable for you
            "cancelurl": "http://...",  # Express checkout cancel url
            "returnurl": "http://..."}  # Express checkout return url

	ppp = PayPalPro(
    	item=item,                            # what you're selling
    	payment_template="payment.html",      # template name for payment
    	confirm_template="confirmation.html", # template name for confirmation
    	success_url="/success/",              # redirect location after success
    	nvp_handler=nvp_handler,
    	)
	
	return ppp(request)

assets/templates/base.html
<!doctype html>
{% load staticfiles %}

<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
        <meta name="description" content="{% block meta_description %}{% endblock %}">
        {% block extra_meta_tags %}{% endblock extra_meta_tags %}

        <title>SlackDroid{% block site_title %}{% endblock site_title %}</title>

        {% block extra_head %}{% endblock extra_head %}

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
        <link rel="shortcut icon" href="/static/img/icon.ico">

        <link href="/static/css/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

        {% block extra_css %}{% endblock extra_css %}

        <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
        <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    </head>
    <body>
        <header>
            {% block header %}
                <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
                    <div class="container topnav">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>-->
                            <img src="/static/img/logo01.gif" class="logo-gif"/>
                            <a class="navbar-brand topnav" href="../profile">SlackDroid</a>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            {% block navtab %}{% endblock navtab %}
                        </div>
                        <!-- /.navbar-collapse -->
                    </div>
                </nav>
            {% endblock header %}
        </header>

        {% block content %}{% endblock content %}

        <footer>
            {% block footer %}{% endblock footer %}
        </footer>

        <script src="{% static 'js/custom.js' %}">
        </script>
        {% block extra_js %}{% endblock extra_js %}
    </body>
</html>

assets/templates/base2.html
{% extends 'base.html' %}

{% block extra_css %}
<style>
    .intro-message {
        font-size: 80px;
        color: white;
        margin: -30px 0px 30px 0px;
        padding: 0px 0px 0px 0px;
        text-shadow: 2px 2px 3px rgba(0,0,0,0.6);
    }

    .huge {
        font-size: 20px;
        margin: 0px 0px 0px 0px;
        color: white;
    }

    .panel-primary {
        border-color: white;
    }

    .panel-primary>.panel-heading {
        border-color: gray;
        background-color: white;
    }

    .panel-heading {
        height: 320px;
    }

    .panel-heading .row-price {
        height: 40px;
    }

    .panel-heading .price {
        background-color: #700202;
        position: absolute;
        right: 10px;
        border-radius: 5px;
        padding: 5px 20px 5px 10px;
    }

    .panel-heading .done {
        margin: 35px 0px 0px 0px;
        padding: 5px 20px 5px 10px;
    }

    .panel-footer {
        background-color: #700202;
    }

    .panel-footer:hover {
        background-color: #420101;
    }

    .img-bot {
        height: 250px;
    }
</style>
{% endblock extra_css %}

{% block navtab %}
<ul class="nav navbar-nav navbar-right">
    <li>
        <a href="../purchase">Purchase</a>
    </li>
    <li>
        <a href="../achievements">Achievements</a>
    </li>
    <li>
        <a href="../payment-url">Payment</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Log Out</a>
    </li>
</ul>
{% endblock navtab %}

{% block content %}
<div class="notnav">
    <div class="container">
        <div class="row">
            <div class="intro-message text-center">
                {% block page_title %}{% endblock page_title %}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row row-price">
                            {% block side_tags1 %}{% endblock side_tags1 %}
                        </div>
                        <div class="row">
                            <div class="row text-center">
                                <img src="/static/img/R10.png" class="img-bot"/>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer text-center">
                        <div class="row">
                            <div class="huge">
                                {% block name_tags1 %}{% endblock name_tags1 %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row row-price">
                            {% block side_tags2 %}{% endblock side_tags2 %}
                        </div>
                        <div class="row">
                            <div class="row text-center">
                                <img src="/static/img/R21.png" class="img-bot"/>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer text-center">
                        <div class="row">
                            <div class="huge">
                                {% block name_tags2 %}{% endblock name_tags2 %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row row-price">
                            {% block side_tags3 %}{% endblock side_tags3 %}
                        </div>
                        <div class="row">
                            <div class="row text-center">
                                <img src="/static/img/R31.png" class="img-bot"/>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer text-center">
                        <div class="row">
                            <div class="huge">
                                {% block name_tags3 %}{% endblock name_tags3 %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row row-price">
                            {% block side_tags4 %}{% endblock side_tags4 %}
                        </div>
                        <div class="row">
                            <div class="row text-center">
                                <img src="/static/img/R41.png" class="img-bot"/>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer text-center">
                        <div class="row">
                            <div class="huge">
                                {% block name_tags4 %}{% endblock name_tags4 %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

assets/templates/confirmation.html
<!-- confirmation.html -->
<h1>Are you sure you want to buy this thing?</h1>
<form method="post" action="">
  {{ form }}
  <input type="submit" value="Yes I Yams">
</form>

assets/templates/payment.html
{% extends 'base.html' %}

{% block extra_css %}
<style>
	label {
		color: white;
	}

	.intro-message {
        font-size: 80px;
        color: white;
        margin: -30px 0px 30px 0px;
        padding: 0px 0px 0px 0px;
        text-shadow: 2px 2px 3px rgba(0,0,0,0.6);
    }

	#donebtnPayPal {
		width: 60%;
		font-weight: 900;
		padding: 5px;
	}

	#id_cvv2,
	#id_expdate_1,
	#id_expdate_0,
	#id_acct,
	#id_zip,
	#id_countrycode,
	#id_state,
	#id_city,
	#id_street,
	#id_lastname,
	#id_firstname, {
		color: black;
	}

	input {
		width: 80%;
		float: right;
	}
	
	#id_countrycode {
		float: right;
	}

	table tbody tr td span {
		float: right;
	}
</style>
{% endblock extra_css %}

{% block navtab %}
<ul class="nav navbar-nav navbar-right">
    <li>
        <a href="../purchase">Purchase</a>
    </li>
    <li>
        <a href="../achievements">Achievements</a>
    </li>
    <li>
        <a href="../payment-url">Payment</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Log Out</a>
    </li>
</ul>
{% endblock navtab %}

{%block content%}
<div class="notnav">
    <div class="container">
    	<div class="row">
    		<div class="intro-message text-center">
    			Paypal Form
    		</div>
    	</div>
        <div class="row">
        	<form method="post" action="">
        		<div class="col-lg-3"></div>
        		<div class="col-lg-6">
        			<div class="row">
			            <table class="table table-condensed">
								{% csrf_token %}
							  	{{ form }}
						</table>
					</row>
					<div class="row">
						<div class="col-lg-8"></div>
        				<div class="col-lg-4">
							<input type="submit" value="Done" id="donebtnPayPal">
						</div>
					</row>
				</div>
			</form>
        </div>
        
    </div>
</div>
{% endblock content %} 

assets/templates/user/achievements.html
{% extends 'base2.html' %}

{% block site_title %}: Achievements{% endblock site_title %}

{% block page_title %}Achievements{% endblock page_title %}

{% block name_tags1 %}Slacker{% endblock name_tags1 %}

{% block name_tags2 %}{% endblock name_tags2 %}

{% block name_tags3 %}{% endblock name_tags3 %}

{% block name_tags4 %}{% endblock name_tags4 %}

assets/templates/user/index.html
{% extends 'base.html' %}

{% block extra_css %}
<!-- Custom CSS -->
<link href="/static/css/landing-page.css" rel="stylesheet">
{% endblock extra_css %}

{% block site_title %}: Log In{% endblock site_title %}

{% block content %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1 id="tagline">Post Now <i class="fa fa-spinner fa-fw"></i> Send Later</h1>
                    <img src="/static/img/lazybot00.png" class="slack"/>
                    <hr>
                    <div class="socialbutton">
	                    <ul class="list-inline intro-social-buttons">
	                        <li>
	                            <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
	                        </li>
	                        <li>
	                            <a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
	                        </li>
	                    </ul>
	                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

assets/templates/user/login.html
{% extends 'base.html' %}
{% block content %}
	<h1>IN</h1>
	<a href="{% url 'users:logout' %}">Logout</a>
{% endblock content %}

assets/templates/user/profile.html
{% extends 'base.html' %}

{% block extra_css %}
<style>
	.row {
		margin-bottom: 10px;
	}

	textarea {
		resize: vertical;
	}

	.profile-img {
		height: 300px;
		text-align: center;
	}

	.img-rounded {
		border: 5px solid white;
	}

	.huge-title {
    	font-size: 30px;
    	margin: 0px 0px 10px 0px;
    	color: white;
	}
	
	.lists {
		background-color: white;
		border-radius: 5px;
		margin: 0px 0px 4px 0px;
		padding: 10px;
	}

	.lists:hover {
		background-color: silver;
	}

	.level {
		padding-top: 5px;
		padding-bottom: 10px;
		color: white;
		font-size: 18px;
		text-align: center;
	}

	.level .intelpoints {
		background-color: #A22811;
		padding: 5px;
		border: 1px solid white;
		border-radius: 5px;
	}

	.level .bot-name {
		background-color: #A22811;
		padding: 5px;
		border: 1px solid white;
		border-radius: 5px;
	}

	.left-part {
		margin-right: -10px;
	}

	.right-part {
		margin-left: -15px;
	}
</style>
{% endblock extra_css %}

{% block site_title %}: Profile{% endblock site_title %}

{% block navtab %}
<ul class="nav navbar-nav navbar-right">
    <li>
        <a href='../purchase'>Purchase</a>
    </li>
    <li>
        <a href="../achievements">Achievements</a>
    </li>
    <li>
        <a href="../payment-url">Payment</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Log Out</a>
    </li>
</ul>
{% endblock navtab %}

{% block content %}
<div class="notnav">
	<div class="container">
		<div class="col-lg-8">
			<form>
		    	<div class="row">
		        	<div class="col-lg-3">
						<select class="form-control">
							<option>---  Social Media ---</option>
							<option value="facebook">Facebook</option>
							<option value="twitter">Twitter</option>
						</select>
		        	</div>
		        	<div class="col-lg-2">
						<select class="form-control">
							<option>--  Hour --</option>
							<option value="1">1 hour</option>
							<option value="2">2 hours</option>
							<option value="24">24 hours</option>
						</select>
		        	</div>
		    	</div>
		    	<div class="row">
		    		<div class="col-lg-12">
						<textarea class="form-control" rows="8" placeholder="TEXT HERE"></textarea>
					</div>
		    	</div>
		    	<div class="row">
		    		<div class="col-lg-10">
		    		</div>
		    		<div class="col-lg-2">
		    			<button type="submit" class="btn btn-default">Send Later</button>
		    		</div>
		    	</div>
		    </form>
		    <div class="row">
				<div class="col-lg-12">
					<hr>
					<span class="huge-title">Queue</span>
					<div class="lists">
						<i class="fa fa-angle-double-right fa-1x fa-fw"></i> edit this
						<span class="pull-right"><i class="fa fa-trash fa-fw"></i></span>
					</div>
					<div class="lists">
						<i class="fa fa-angle-double-right fa-1x fa-fw"></i> edit this
						<span class="pull-right"><i class="fa fa-trash fa-fw"></i></span>
					</div>
					<div class="lists">
						<i class="fa fa-angle-double-right fa-1x fa-fw"></i> edit this
						<span class="pull-right"><i class="fa fa-trash fa-fw"></i></span>
					</div>
					<div class="lists">
						<i class="fa fa-angle-double-right fa-1x fa-fw"></i> edit this
						<span class="pull-right"><i class="fa fa-trash fa-fw"></i></span>
					</div>
					<div class="lists">
						<i class="fa fa-angle-double-right fa-1x fa-fw"></i> edit this
						<span class="pull-right"><i class="fa fa-trash fa-fw"></i></span>
					</div>
					<div class="lists">
						<i class="fa fa-angle-double-right fa-1x fa-fw"></i> edit this
						<span class="pull-right"><i class="fa fa-trash fa-fw"></i></span>
					</div>
				</div>
		    </div>
		</div>
		<div class="col-lg-4">
			<div class="col-lg-1">
			</div>
			<div class="col-lg-10">
				<div class="row">
					<div class="col-lg-12 text-center">
						<img src="/static/img/R20.png" class="profile-img"/>
					</div>
				</div>
				<div class="row level">
					<div class="col-lg-5">
						<div class="intelpoints left-part">
							0000 <i class="fa fa-lightbulb-o fa-1x"></i>
						</div>
					</div>
					<div class="col-lg-7">
						<div class="bot-name right-part">
							Facebook Droid <i class="fa fa-male fa-1x"></i>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<span class="huge-title">Activity</span>
						<div class="lists">
							<i class="fa fa-check fa-1x fa-fw"></i> edit this
						</div>
						<div class="lists">
							<i class="fa fa-check fa-1x fa-fw"></i> edit this
						</div>
						<div class="lists">
							<i class="fa fa-check fa-1x fa-fw"></i> edit this
						</div>
						<div class="lists">
							<i class="fa fa-check fa-1x fa-fw"></i> edit this
						</div>
						<div class="lists">
							<i class="fa fa-check fa-1x fa-fw"></i> edit this
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

assets/templates/user/purchase.html
{% extends 'base2.html' %}

{% block site_title %}: Purchase{% endblock site_title %}

{% block page_title %}Purchase Bots{% endblock page_title %}

{% block side_tags1 %}
<div class="price">
    FREE
</div>
<div class="price done">
    DONE
</div>
{% endblock side_tags1 %}

{% block side_tags2 %}
<div class="price">
    300
</div>
{% endblock side_tags2 %}

{% block side_tags3 %}
<div class="price">
    800
</div>
{% endblock side_tags3 %}

{% block side_tags4 %}
<div class="price">
    1500
</div>
{% endblock side_tags4 %}

{% block name_tags1 %}Slacker{% endblock name_tags1 %}

{% block name_tags2 %}Purchase{% endblock name_tags2 %}

{% block name_tags3 %}Purchase{% endblock name_tags3 %}

{% block name_tags4 %}Purchase{% endblock name_tags4 %}